ALTER TABLE DVM_ERRORS_EXCLUDE
RENAME TO DVM_ISSUES_EXCLUDE;

ALTER TABLE DVM_ISSUES_EXCLUDE RENAME COLUMN ERROR_ID TO ISS_ID;

ALTER INDEX DVM_ERRORS_EXCLUDE_PK
RENAME TO DVM_ISSUES_EXCLUDE_PK;

ALTER TABLE DVM_ISSUES_EXCLUDE
RENAME CONSTRAINT DVM_ERRORS_EXCLUDE_PK TO DVM_ISSUES_EXCLUDE_PK;

ALTER TABLE DVM_ISSUES_EXCLUDE
RENAME CONSTRAINT DVM_ERRORS_EXCLUDE_FK TO DVM_ISSUES_EXCLUDE_FK;
